### ISSUE TITLE
Output Label

### ISSUE THREAD

**Issue by pftnhr** [GiovanniSalmeri/yellow-diary#4]
Is there a way to output the label?

**Comment by GiovanniSalmeri** [comment]
I didn't plane it because I thought the label only as an internal token for disambiguating events with the same date, but it is very easy to output it. Just add something like this between between lines 145 and 153 in `diary.php`:

`$output .= "<div class=\"label\">".htmlspecialchars($event[3])."</div>\n";`

Not tested, but it should work :-)

**Comment by pftnhr** [comment]
It works! :D 

Thanks a lot!
